# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d394e8a150e87c4d463fac05d60dc9d3e9043b818768311f7b300f50efd7c5459cdf7cf2143a4f39f624d0e3d14f22d8c7d012d29508ccb660b9a857e0e1f8

test:
  secret_key_base: 07646a933a4cab18e56fed951596ad733155273736c9a36d8cba859f50003c5c1e60568e2e7ab80f6e6db941a2a65dd9f09423ed01aa1097bc096e35c75dc1d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
